name: win-2 
# clones all 

on:
  workflow_dispatch:
  # Trigger the workflow on push or pull request - but only for the main branch
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: cmd

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # windows-latest or windows-2022 fail!?
    runs-on: windows-2025

    steps:
    - run: choco install wget innoextract --no-progress


    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Clone dependencies
      working-directory: ${{ github.workspace }}
      run: |
          cd "${{ github.workspace }}"
          git clone https://github.com/marzer/tomlplusplus tomlplusplus
          git clone https://github.com/libusb/libusb libusb
          git clone https://github.com/trev90211/rtl-sdr
          git clone https://github.com/GerHobbelt/pthread-win32 pthread-win32
          echo "********************************************"
          echo "dir -lash"
          dir -lash
          echo "********************************************"
          echo "dir -lasR"
          dir -lasR
          echo "********************************************"
          echo "runner.workspace  ${{ runner.workspace }} /s"
          dir -las "${{ runner.workspace }}" 
          echo "********************************************"
          echo "github.workspace  ${{ github.workspace }}/pthread-win32/static"
          dir -las "${{ github.workspace }}/pthread-win32"
          echo "********************************************"
          echo "github.workspace  ${{ github.workspace }}/libusb"
          dir -las "${{ github.workspace }}/libusb"
          echo "********************************************"
          echo "github.workspace  ${{ github.workspace }}"
          dir -las "${{ github.workspace }}"
          echo "********************************************"
    - name: Build pthread-win32
      working-directory: ${{ github.workspace }}
      run: |
          cd pthread-win32
          cmake -B "${{github.workspace}}/pthread-win32/static" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/pthread-win32/static"
          cmake --build "${{github.workspace}}/pthread-win32/static" --config Release --target install
          echo "********************************************"
          echo "dir /s"
          dir -lash
          echo "********************************************"
          echo "github.workspace  ${{ github.workspace }} /s"
          dir -lash "${{ github.workspace }}"
          echo "********************************************"
          echo "runner.workspace  ${{ runner.workspace }}"
          dir -lasR "${{ runner.workspace }}"
          #cd ..
          #echo "pgms"
          #dir -lash "/c/"
          #dir -lash "/c/ProgramData"
          #dir -lash "/c/ProgramData/Chocolatey"
          #dir -lash "/c/ProgramData/Chocolatey/bin"
          #dir -lash "/c/Program Files"
          #dir -lash "/c/Program Files/MSBuild"
          #dir -lash "/c/Program Files/MSBuild/Microsoft"
          #dir -lash "/c/Program Files/MSBuild/Microsoft/Windows Workflow Foundation"
          #dir -lash "/c/Program Files/MSBuild/Microsoft/Windows Workflow Foundation/v3.0"
          #dir -lash "/c/Program Files/MSBuild/Microsoft/Windows Workflow Foundation/v3.0/Workflow.Targets"
          #dir -lash "/c/Program Files/MSBuild/Microsoft/Windows Workflow Foundation/v3.5"
          #dir -lash "/c/Program Files/MSBuild/Microsoft/Windows Workflow Foundation/v3.5/Workflow.Targets"

          #cd "/c/Program Files/"
          #find . -name MSBuild.exe

          #cd "/c/Program Files (x86)/"
          #find . -name MSBuild.exe
          
          #dir -lasR "/c/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin"
          #dir -lasR "/c/Program Files (X86)/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin"
          
          #echo $"(/c/ProgramData/Chocolatey/bin/vswhere.exe  -latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe)"
          
          #echo $"(/c/ProgramData/Chocolatey/bin/vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest)"

          #PATH=$PATH:"/c/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64"
          PATH=$PATH:"/c/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin"
          echo $PATH

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure Visual Studio and CMake
        working-directory: ${{runner.workspace}}
        run: |
            cd ${{ github.workspace }}
            # setup the compiler
            cmd.exe /c "call `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
            Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
            # run cmake, looks v141_xp Toolset requires VS 2019
            cmake -G "Visual Studio 17 2022" -A Win32 -S libusb -B build_libusb
            cmd.exe /c dir /s

          echo "********************************************"
          echo "dir /s"
          dir -lash
          dir -lasR
          echo "********************************************"
          cd ..

    - name: Configure Visual Studio and CMake
      working-directory: ${{ runner.workspace }}
      run: |
          cd ${{ github.workspace }}
          dir 
          #dir "d:\a\ExtIO_RTL_h\ExtIO_RTL_h\pthread-win32\" 
          #dir "c:\Program Files (x86)\Microsoft Visual Studio/installer"
          #dir "c:\Program Files (x86)\Microsoft Visual Studio/shared"
          #dir "c:\Program Files (x86)\Microsoft Visual Studio 14.0/SDK"
          #dir "c:\Program Files\Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/build"
          #dir "c:\Program Files\Microsoft Visual Studio 14.0/common7"
          # setup the compiler
          "call `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
          type %temp%\vcvars.txt
          type temp\vcvars.txt
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
          set
          # run cmake, looks v141_xp Toolset requires VS 2019
          cmake -G "Visual Studio 17 2022" -A Win32 -S ExtIO_RTL_h -B build_librtlsdr \
                -DTHREADS_PTHREADS_INCLUDE_DIR='${{github.workspace}}/pthread-win32/static/include' \
                -DTHREADS_PTHREADS_LIBRARY='${{github.workspace}}/pthread-win32/static/lib/pthreadVC3.lib' \
                -DLIBUSB_LIBRARY='${{github.workspace}}/libusb/Release/lib/libusb-1.0.lib' \
                -DLIBUSB_INCLUDE_DIRS='${{github.workspace}}/libusb/include/libusb-1.0' .

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: cmake --build build_librtlsdr --config $BUILD_TYPE --target librtlsdr

    #- name: Dir Listing
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: find . >src_listing.txt

    - name: Collect files to distribute
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        cp "${{github.workspace}}/ExtIO_RTL/README.md" ./
        cp "${{github.workspace}}/ExtIO_RTL/COPYING" ./LICENSE
        cp "${{github.workspace}}/build_librtlsdr/Release/ExtIO_RTL.dll" ./

    - name: package and upload
      uses: actions/upload-artifact@v4
      with:
        name: extio_rtl
        path: |
            ${{github.workspace}}/ExtIO_RTL.dll
            ${{github.workspace}}/README.md
            ${{github.workspace}}/LICENSE
