name: win-3
# clones all 

on:
  workflow_dispatch:
  # Trigger the workflow on push or pull request - but only for the main branch
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: PowerShell

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-windows:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    # windows-latest or windows-2022 fail!?
    runs-on: windows-2025

    steps:
    - run: choco install wget innoextract --no-progress


    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Clone dependencies
      working-directory: ${{ github.workspace }}
      run: |
          cd "${{ github.workspace }}"
          git clone https://github.com/marzer/tomlplusplus tomlplusplus
          git clone https://github.com/libusb/libusb libusb
          git clone https://github.com/trev90211/rtl-sdr
          git clone https://github.com/GerHobbelt/pthread-win32 pthread-win32
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "dir /s"
          cmd.exe /c dir /s
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "runner.workspace  ${{ runner.workspace }} /s"
          cmd.exe /c dir "${{ runner.workspace }}" /s
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "github.workspace  ${{ github.workspace }}/pthread-win32/static"
          cmd.exe /c dir "${{ github.workspace }}/pthread-win32" /s
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "github.workspace  ${{ github.workspace }}/libusb"
          cmd.exe /c dir "${{ github.workspace }}/libusb" /s
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "github.workspace  ${{ github.workspace }}"
          cmd.exe /c dir "${{ github.workspace }}" /s
          cmd.exe /c echo "********************************************"
    - name: Build pthread-win32
      working-directory: ${{ github.workspace }}
      run: |
          cd pthread-win32
          cmake -B "${{github.workspace}}/pthread-win32/static" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/pthread-win32/static"
          cmake --build "${{github.workspace}}/pthread-win32/static" --config Release --target install
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "dir /s"
          cmd.exe /c dir /s
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "github.workspace  ${{ github.workspace }} /s"
          cmd.exe /c dir "${{ github.workspace }}" /s
          cmd.exe /c echo "********************************************"
          cmd.exe /c echo "runner.workspace  ${{ runner.workspace }}"
          cmd.exe /c dir "${{ runner.workspace }}" /s
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: libusb Configure Visual Studio and CMake
      working-directory: ${{github.workspace}}
      run: |
          msbuild libusb/msvc/libusb.sln /m -property:Configuration=Release -property:Platform=Win32

          echo "********************************************"
          echo "dir /s"
          dir /s
          dir ..
          dir ../..
          echo "********************************************"
          cd ..



    - name: RTL-SDR build
      run: |
        mkdir ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake -A x64 -DCMAKE_BUILD_TYPE=Release \
              -DLIBUSB_LIBRARIES=${{github.workspace}}/libusb/VS2019/MS64/Release/lib/libusb-1.0.lib \
              -DLIBUSB_INCLUDE_DIRS=${{github.workspace}}/libusb/include/libusb-1.0 \
              -DTHREADS_PTHREADS_INCLUDE_DIR=${{github.workspace}}/pthreads/Pre-built.2/include \
              -DTHREADS_PTHREADS_LIBRARY=${{github.workspace}}/pthreads/Pre-built.2/lib/x86/pthreadVC2.lib ..
        cmake --build . --parallel $NUMBER_OF_PROCESSORS --config Release
        cmake --install . --prefix ${{github.workspace}}/dist --config Release
        ###echo "* ${{github.workspace}} : `git show --format='%h (%s, %as)' --no-patch`" >> ${{github.workspace}}/release_notes.md
        ls -lashR ${{github.workspace}}

    - name: Build
      working-directory: ${{runner.workspace}}
      #shell: bash
      run: cmake --build build_librtlsdr --config Release --target librtlsdr

    #- name: Dir Listing
    #  working-directory: ${{runner.workspace}}
    #  shell: bash
    #  run: find . >src_listing.txt

    - name: Collect files to distribute
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        #cp "${{github.workspace}}/ExtIO_RTL/README.md" ./
        #cp "${{github.workspace}}/ExtIO_RTL/COPYING" ./LICENSE
        cp "${{github.workspace}}/Release/*" ./

    - name: package and upload
      uses: actions/upload-artifact@v4
      with:
        name: librtlsdr
        path: |
            ${{github.workspace}}/ExtIO_RTL.dll
            ${{github.workspace}}/README.md
            ${{github.workspace}}/LICENSE













